bigip_cluster_health_f5_provider:
  server: "{{ ansible_host }}"
  user: "{{ ansible_user }}"
  password: "{{ ansible_password }}!"
  validate_certs: " {{ verify_host_certificate }} "

bigip_cluster_health_health_check_endpoints:
  - name: "Cluster Sync Status"
    uri: "/mgmt/tm/cm/sync-status"
  - name: "Cluster Traffic Group Status"
    uri: "/mgmt/tm/cm/traffic-group"
